#!/usr/bin/env python3
"""Build the TLS trust bundle the firmware passes to esp_crt_bundle_set().

Reads every PEM certificate under certs/ and writes
src/network/CrtBundle.generated.h in the ESP-IDF x509 bundle format
(offset table + per-cert subject DER and SubjectPublicKeyInfo DER, sorted by
subject bytes). Runs automatically as a PlatformIO pre-script and can also be
run by hand:

    python3 scripts/gen_crt_bundle.py [certs_dir] [output_header]

Why a custom bundle: the default IDF bundle holds only root CAs, so verifying
a Let's Encrypt chain means an RSA-4096 signature check against ISRG Root X1.
On the ESP32-C3 that operation runs in software at the memory peak of the TLS
handshake and fails with MBEDTLS_ERR_MPI_ALLOC_FAILED (seen as "PK verify
failed with error 0x4290"). Adding the issuing intermediates as trust anchors
lets verification stop at the intermediate's 2048-bit RSA or ECDSA key.
"""

import base64
import os
import struct
import sys

MAX_CERTS = 200  # CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_MAX_CERTS


def read_tlv(data: bytes, pos: int):
    """Return (tag, header_len, value_len) for the DER element at pos."""
    tag = data[pos]
    length = data[pos + 1]
    header = 2
    if length & 0x80:
        count = length & 0x7F
        length = int.from_bytes(data[pos + 2 : pos + 2 + count], "big")
        header += count
    return tag, header, length


def children(data: bytes, pos: int):
    """Yield (tag, start, end) for each child TLV of the constructed element at pos."""
    _tag, header, length = read_tlv(data, pos)
    cursor = pos + header
    end = cursor + length
    while cursor < end:
        tag, child_header, child_length = read_tlv(data, cursor)
        child_end = cursor + child_header + child_length
        yield tag, cursor, child_end
        cursor = child_end


def subject_and_key(der: bytes):
    cert_children = list(children(der, 0))
    tbs_tag, tbs_start, _ = cert_children[0]
    if tbs_tag != 0x30:
        raise ValueError("tbsCertificate is not a SEQUENCE")
    fields = list(children(der, tbs_start))
    if fields[0][0] == 0xA0:  # explicit version tag
        fields = fields[1:]
    # serialNumber, signature, issuer, validity, subject, subjectPublicKeyInfo
    _, subject_start, subject_end = fields[4]
    _, spki_start, spki_end = fields[5]
    return der[subject_start:subject_end], der[spki_start:spki_end]


def load_pems(certs_dir: str):
    ders = []
    for name in sorted(os.listdir(certs_dir)):
        if not name.endswith(".pem"):
            continue
        with open(os.path.join(certs_dir, name), encoding="utf-8", errors="replace") as f:
            block = []
            inside = False
            for line in f:
                line = line.strip()
                if line == "-----BEGIN CERTIFICATE-----":
                    inside, block = True, []
                elif line == "-----END CERTIFICATE-----":
                    inside = False
                    ders.append(base64.b64decode("".join(block)))
                elif inside:
                    block.append(line)
    return ders


def build_bundle(ders):
    entries = {}
    for der in ders:
        subject, key = subject_and_key(der)
        entries[(subject, key)] = None  # dedupe
    certs = sorted(entries.keys(), key=lambda e: e[0])
    if len(certs) > MAX_CERTS:
        raise ValueError(f"{len(certs)} certificates exceed the firmware limit of {MAX_CERTS}")

    body = bytearray()
    offsets = []
    table_size = 4 * len(certs)
    for subject, key in certs:
        offsets.append(table_size + len(body))
        body += struct.pack("<HH", len(subject), len(key))
        body += subject
        body += key
    return struct.pack("<%dI" % len(offsets), *offsets) + bytes(body), len(certs)


def write_header(path: str, bundle: bytes, count: int):
    lines = ["// Generated by scripts/gen_crt_bundle.py from certs/*.pem. Do not edit.", "#pragma once", "#include <cstdint>", "",
             f"// {count} certificates, {len(bundle)} bytes", "static const uint8_t CRT_BUNDLE[] = {"]
    for i in range(0, len(bundle), 16):
        lines.append("    " + ", ".join("0x%02X" % b for b in bundle[i : i + 16]) + ",")
    lines.append("};")
    content = "\n".join(lines) + "\n"
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            if f.read() == content:
                return False
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return True


def main(certs_dir=None, output=None):
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    certs_dir = certs_dir or os.path.join(root, "certs")
    output = output or os.path.join(root, "src", "network", "CrtBundle.generated.h")
    bundle, count = build_bundle(load_pems(certs_dir))
    changed = write_header(output, bundle, count)
    print(f"crt bundle: {count} certificates, {len(bundle)} bytes -> {output}{'' if changed else ' (unchanged)'}")


if __name__ == "__main__":
    main(*(sys.argv[1:3]))
else:
    try:
        Import("env")  # noqa: F821  (PlatformIO pre-script context)
        main()
    except NameError:
        pass
